//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.GetPetList {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetPetList.PetsSoap")]
    public interface PetsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPetList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PetsSoapChannel : Pet_Shop.GetPetList.PetsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PetsSoapClient : System.ServiceModel.ClientBase<Pet_Shop.GetPetList.PetsSoap>, Pet_Shop.GetPetList.PetsSoap {
        
        public PetsSoapClient() {
        }
        
        public PetsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PetsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PetsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPetList() {
            return base.Channel.GetPetList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPetListAsync() {
            return base.Channel.GetPetListAsync();
        }
    }
}
